- name: ne_deva
  weight: 0.40
  equal_split: true
  sources:
    - himalaya-ai/nepali-corpus-compile
    - himalaya-ai/nepali-pretrain-corpus
    - ai4bharat/sangraha:verified:nep
  shard_prefix: pretrain_ne_deva
  log: data/pretrain_ne_deva.log

- name: deva_mix
  weight: 0.05
  equal_split: true
  sources:
    - himalaya-ai/devanagari_pretrain
  shard_prefix: pretrain_deva_mix
  log: data/pretrain_deva_mix.log

- name: hi_deva
  weight: 0.18
  equal_split: true
  sources:
    - ai4bharat/sangraha:verified:hin
    - ai4bharat/IndicCorpV2:indiccorp_v2:hin_Deva
    - zicsx/OSCAR-2301-Hindi
    - uvaidya/hindi-fineweb2-40b
  shard_prefix: pretrain_hi_deva
  log: data/pretrain_hi_deva.log

- name: en
  weight: 0.18
  equal_split: true
  sources:
    - HuggingFaceFW/fineweb-edu
    - mlfoundations/dclm-baseline-1.0
  shard_prefix: pretrain_en
  log: data/pretrain_en.log

- name: code
  weight: 0.07
  equal_split: true
  sources:
    - OpenCoder-LLM/opc-fineweb-code-corpus
    - ronantakizawa/github-top-code
  shard_prefix: pretrain_code
  log: data/pretrain_code.log

- name: math
  weight: 0.03
  equal_split: true
  sources:
    - OpenCoder-LLM/opc-fineweb-math-corpus
    - HuggingFaceTB/finemath:finemath-3plus:train
  shard_prefix: pretrain_math
  log: data/pretrain_math.log

- name: roman_ne
  weight: 0.04
  equal_split: true
  sources:
    - himalaya-ai/nepali-roman-pretrain
  shard_prefix: pretrain_roman_ne
  log: data/pretrain_roman_ne.log

- name: indic_latn
  weight: 0.04
  equal_split: true
  sources:
    - himalaya-ai/indic_latn_pretrain
  shard_prefix: pretrain_indic_latn
  log: data/pretrain_indic_latn.log

- name: roman_hi
  weight: 0.01
  equal_split: true
  sources:
    - ai4bharat/sangraha:synthetic:hin_Latn
  shard_prefix: pretrain_roman_hi
  log: data/pretrain_roman_hi.log
